@extends('layouts')

@section('content')
    <div class="container mt-5">
        <h2 class="mb-4">Reports Dashboard</h2>

        <div class="row g-4">
            <!-- Purchase Report Card -->
            <div class="col-md-4">
                <div class="card shadow-sm border-primary h-100 report-card">
                    <div class="card-body text-center">
                        <div class="mb-3">
                            <i class="bi bi-cart-check-fill" style="font-size: 2.5rem; color:#0d6efd;"></i>
                        </div>
                        <h5 class="card-title mb-3">Purchase Report</h5>
                        <p class="card-text">View all purchase details including suppliers, totals, and invoices.</p>
                        <a href="{{ route('reports.purchases') }}" class="btn btn-primary">View Report</a>
                    </div>
                </div>
            </div>

            <!-- Profit & Loss Card -->
            <div class="col-md-4">
                <div class="card shadow-sm border-success h-100 report-card">
                    <div class="card-body text-center">
                        <div class="mb-3">
                            <i class="bi bi-currency-dollar" style="font-size: 2.5rem; color:#198754;"></i>
                        </div>
                        <h5 class="card-title mb-3">Profit & Loss</h5>
                        <p class="card-text">Check the overall profit or loss generated by sales and purchases.</p>
                        <a href="{{ route('reports.profit-loss') }}" class="btn btn-success">View Profit & Loss</a>
                    </div>
                </div>
            </div>

            <!-- Stock Report Card -->
            <div class="col-md-4">
                <div class="card shadow-sm border-warning h-100 report-card">
                    <div class="card-body text-center">
                        <div class="mb-3">
                            <i class="bi bi-box-seam" style="font-size: 2.5rem; color:#ffc107;"></i>
                        </div>
                        <h5 class="card-title mb-3">Stock Report</h5>
                        <p class="card-text">View current stock levels and low stock alerts for all products.</p>
                        <a href="{{ route('reports.stock') }}" class="btn btn-warning text-white">View Stock</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Optional Custom CSS -->
    <style>
        .report-card:hover {
            transform: translateY(-5px);
            transition: 0.3s;
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.15);
        }
    </style>
@endsection